name: Build and Push to AWS ECR
on:
  push:
    branches:
      - main
permissions:
  contents: read
  id-token: write  # Required for OIDC authentication with AWS
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Set up AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: true
        registry-type: private
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.ECR_REPOSITORY_URI }}:latest .
    - name: Tag Docker image
      run: |
        docker tag ${{ secrets.ECR_REPOSITORY_URI }}:latest ${{ secrets.ECR_REPOSITORY_URI }}:latest
    - name: Push Docker image to Amazon ECR
      run: |
        docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest